Homework1
made-ml-in-prod-2021/andyst75 pull request #2
Opened 2021-05-06 19:07 UTC by andyst75

Был проведен EDA, на основании было выбрано 2 модели: Random Forest Classifier и Multinomial NB.
В проекте используется hydra_core, что позволяет гибко настраивать нужные модели и трансформации.
Модели и трансформеры задаются гибко через файлы конфигурации и к ним есть всего 2 требования:
1. они должны наследоваться от sklearn.base.BasicEstimator
2. им должны передаваться параметры
Высокое покрытие тестами (pytest --cov дает 98,1%) и высокое соответствие PEP (pylint оценивает в 9.89)
Настроена проверка при коммитах на гитхаб.

2021-05-10 11:26 UTC, EvgeniiMunin reviewed
на проверку взял

2021-05-10 12:49 UTC, EvgeniiMunin reviewed
Проверил ПР. Написал несколько комментариев по разделу тестов. В принципе, считаю, что работа образцовая и соответствует максимальному баллу. На месте полностью кастомный трансформер, логирование, конфиги + несколько пайплайнов и покрытие тесами.

2021-05-10 12:49 UTC, EvgeniiMunin commented on ml_project/tests/data/test_data_transformer.py
> +    assert x_data.shape == (FAKE_DATASET_SIZE, FAKE_DATASET_TRANSFORM_COLUMNS)
transform_path определен выше как функция, лучше явно указать тип аргумент, чтобы было понятно, что 
это не инстанс функции

2021-05-10 12:49 UTC, EvgeniiMunin commented on ml_project/tests/data/test_dataset.py
> +    check_result, categorical, numerical = check_data(data, feature_params)
Если numerical, categorical далее нигде не используются, лучше заменить их на _, _

2021-05-10 12:49 UTC, EvgeniiMunin commented on ml_project/src/classes/config_params.py
> +    split: SplittingParams = MISSING
Обязательно ли указывать MISSING, или эти поля умолчанию задаются обязательными ?

2021-05-10 13:57 UTC, andyst75 commented on ml_project/src/classes/config_params.py
> +    split: SplittingParams = MISSING
Насколько я разобрался в вопросе, то MISSING указывает на обязательность поля.

2021-05-10 14:05 UTC, andyst75 commented on ml_project/tests/data/test_data_transformer.py
> +    assert x_data.shape == (FAKE_DATASET_SIZE, FAKE_DATASET_TRANSFORM_COLUMNS)
Исправил.

2021-05-10 15:07 UTC, EvgeniiMunin approved these changes
Approved

2021-05-15 10:08 UTC, ol-ga-00 requested changes
Что касается кастомного трансформера, то это не совсем то что ожидалось, предполагалось, что будет реализован класс с новой функциональность, который затем можно будет пробрасывать в Pipeline. Здесь же, кажется, что функционал реализованного класса перекрывается уже имеющимся в примере Михаила ColumnTransformer. Написано, впрочем неплохо, поэтому 1.5 балла
Или же вы можете реализовать правильный трансформер (то, что ожидалось), чтобы получить 3 баллы

Прошу написать, будуте ли вы реализовывать правильный трансформер, или остановимся на имеющемся

2021-05-15 10:22 UTC, andyst75 commented
> 
> 
> Что касается кастомного трансформера, то это не совсем то что ожидалось, предполагалось, что будет реализован класс с новой функциональность, который затем можно будет пробрасывать в Pipeline. Здесь же, кажется, что функционал реализованного класса перекрывается уже имеющимся в примере Михаила ColumnTransformer. Написано, впрочем неплохо, поэтому 1.5 балла
> Или же вы можете реализовать правильный трансформер (то, что ожидалось), чтобы получить 3 баллы
> 
> Прошу написать, будуте ли вы реализовывать правильный трансформер, или остановимся на имеющемся

Остановимся на текущем варианте.

2021-05-15 10:58 UTC, ol-ga-00 approved these changes
Ставлю 35.5 баллов

2021-05-15 16:13 UTC, merged